services:

  evolution-postgres:
    image: postgres:15
    container_name: evolution_postgres
    restart: always

    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution
      POSTGRES_DB: evolution

    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always

    depends_on:
      - evolution-postgres

    ports:
      - "8080:8080"

    command: >
      sh -c "apk update &&
      apk add --no-cache chromium &&
      npm run start:prod"

    environment:
      SERVER_URL: http://localhost:8080
      AUTHENTICATION_API_KEY: orionsystems

      DATABASE_ENABLED: true
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://evolution:evolution@evolution-postgres:5432/evolution

      CACHE_REDIS_ENABLED: false

      CONFIG_SESSION_PHONE_CLIENT: Evolution API
      CONFIG_SESSION_PHONE_NAME: Chrome
      CONFIG_SESSION_PHONE_VERSION: 2.3000.1023204200

      QRCODE_LIMIT: 30

    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
  evolution_postgres_data: